/*============================================
  CONFIGURACIÓN DE TEMAS Y TIPOGRAFÍAS
  ============================================
  - themes: paletas de colores completas
  - fonts: opciones tipográficas disponibles
  - themeIcons: iconos para cada tema
*/

import {
  FaSun, FaMoon, FaLeaf, FaSeedling,
  FaFire, FaSnowflake, FaHatWizard, FaBolt
} from "react-icons/fa6";

/* ---- ICONOS PARA CADA TEMA ---- */
const themeIcons = {
  light: FaSun,
  midnight: FaMoon,
  forest: FaLeaf,
  sakura: FaSeedling,
  sunset: FaFire,
  arctic: FaSnowflake,
  dracula: FaHatWizard,
  carbon: FaBolt,
};

/* ---- OPCIONES TIPOGRÁFICAS DISPONIBLES ---- */
const fonts = [
  {
    id: "inter",
    name: "Inter",
    family: {
      sans: "'Inter', system-ui, -apple-system, sans-serif",
      heading: "'Inter', system-ui, -apple-system, sans-serif",
      mono: "ui-monospace, 'Cascadia Code', Consolas, monospace",
    },
    category: "sans-serif",
    import: "@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');",
  },
  {
    id: "dm-sans",
    name: "DM Sans",
    family: {
      sans: "'DM Sans', system-ui, sans-serif",
      heading: "'DM Sans', system-ui, sans-serif",
      mono: "ui-monospace, 'Cascadia Code', Consolas, monospace",
    },
    category: "sans-serif",
    import: "@import url('https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500;9..40,600;9..40,700;9..40,800&display=swap');",
  },
  {
    id: "space-grotesk",
    name: "Space Grotesk",
    family: {
      sans: "'Space Grotesk', system-ui, sans-serif",
      heading: "'Space Grotesk', system-ui, sans-serif",
      mono: "ui-monospace, 'Cascadia Code', Consolas, monospace",
    },
    category: "sans-serif",
    import: "@import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap');",
  },
  {
    id: "syne",
    name: "Syne",
    family: {
      sans: "'Syne', system-ui, sans-serif",
      heading: "'Syne', system-ui, sans-serif",
      mono: "ui-monospace, 'Cascadia Code', Consolas, monospace",
    },
    category: "sans-serif",
    import: "@import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;500;600;700;800&display=swap');",
  },
  {
    id: "unbounded",
    name: "Unbounded",
    family: {
      sans: "'Unbounded', system-ui, sans-serif",
      heading: "'Unbounded', system-ui, sans-serif",
      mono: "ui-monospace, 'Cascadia Code', Consolas, monospace",
    },
    category: "sans-serif",
    import: "@import url('https://fonts.googleapis.com/css2?family=Unbounded:wght@300;400;500;600;700&display=swap');",
  },
  {
    id: "archivo",
    name: "Archivo",
    family: {
      sans: "'Archivo', system-ui, sans-serif",
      heading: "'Archivo', system-ui, sans-serif",
      mono: "ui-monospace, 'Cascadia Code', Consolas, monospace",
    },
    category: "sans-serif",
    import: "@import url('https://fonts.googleapis.com/css2?family=Archivo:wght@300;400;500;600;700;800&display=swap');",
  },
  {
    id: "sora",
    name: "Sora",
    family: {
      sans: "'Sora', system-ui, sans-serif",
      heading: "'Sora', system-ui, sans-serif",
      mono: "ui-monospace, 'Cascadia Code', Consolas, monospace",
    },
    category: "sans-serif",
    import: "@import url('https://fonts.googleapis.com/css2?family=Sora:wght@300;400;500;600;700;800&display=swap');",
  },
  {
    id: "playfair",
    name: "Playfair Display",
    family: {
      sans: "system-ui, 'Segoe UI', Roboto, sans-serif",
      heading: "'Playfair Display', Georgia, 'Times New Roman', serif",
      mono: "ui-monospace, 'Cascadia Code', Consolas, monospace",
    },
    category: "serif",
    import: "@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500&display=swap');",
  },
];

/* ---- PALETAS DE COLORES (TEMAS) ---- */
const themes = [
  {
    id: "light",
    name: "Light",
    icon: "light",
    fontId: "inter",
    cursor: "#2563EB",
    preview: ["#FFFFFF", "#2563EB", "#111827"],
    colors: {
      background: "#FFFFFF",
      backgroundSecondary: "#F8FAFC",
      surface: "#F3F4F6",
      surfaceHover: "#E5E7EB",
      text: "#111827",
      textSecondary: "#6B7280",
      primary: "#2563EB",
      primaryHover: "#1D4ED8",
      success: "#22C55E",
      warning: "#F59E0B",
      danger: "#EF4444",
      border: "#E5E7EB",
      shadow: "0 8px 24px rgba(15, 23, 42, 0.08)",
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    icon: "midnight",
    fontId: "syne",
    cursor: "#38BDF8",
    preview: ["#0F172A", "#38BDF8", "#F8FAFC"],
    colors: {
      background: "#0F172A",
      backgroundSecondary: "#1E293B",
      surface: "#1E293B",
      surfaceHover: "#334155",
      text: "#F8FAFC",
      textSecondary: "#CBD5E1",
      primary: "#38BDF8",
      primaryHover: "#0EA5E9",
      success: "#4ADE80",
      warning: "#FBBF24",
      danger: "#F87171",
      border: "#334155",
      shadow: "0 8px 24px rgba(0,0,0,.45)",
    },
  },
  {
    id: "forest",
    name: "Forest",
    icon: "forest",
    fontId: "sora",
    cursor: "#34D399",
    preview: ["#0B1D13", "#34D399", "#E5F9EC"],
    colors: {
      background: "#0B1D13",
      backgroundSecondary: "#143322",
      surface: "#1D4732",
      surfaceHover: "#265A40",
      text: "#E5F9EC",
      textSecondary: "#A7D7BB",
      primary: "#34D399",
      primaryHover: "#10B981",
      success: "#22C55E",
      warning: "#FBBF24",
      danger: "#F87171",
      border: "#2C6248",
      shadow: "0 8px 24px rgba(0,0,0,.35)",
    },
  },
  {
    id: "sakura",
    name: "Sakura",
    icon: "sakura",
    fontId: "dm-sans",
    cursor: "#EC4899",
    preview: ["#FFF7FA", "#EC4899", "#5A2940"],
    colors: {
      background: "#FFF7FA",
      backgroundSecondary: "#FFF1F5",
      surface: "#FFE4EC",
      surfaceHover: "#FFD4E5",
      text: "#5A2940",
      textSecondary: "#8A5B73",
      primary: "#EC4899",
      primaryHover: "#DB2777",
      success: "#22C55E",
      warning: "#F59E0B",
      danger: "#E11D48",
      border: "#F8C7DA",
      shadow: "0 8px 24px rgba(236,72,153,.15)",
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    icon: "sunset",
    fontId: "archivo",
    cursor: "#F97316",
    preview: ["#FFF5EB", "#F97316", "#5B341D"],
    colors: {
      background: "#FFF5EB",
      backgroundSecondary: "#FFF0E0",
      surface: "#FFE3C2",
      surfaceHover: "#FFD5A8",
      text: "#5B341D",
      textSecondary: "#8B5A3C",
      primary: "#F97316",
      primaryHover: "#EA580C",
      success: "#22C55E",
      warning: "#FBBF24",
      danger: "#EF4444",
      border: "#F7CFA6",
      shadow: "0 8px 24px rgba(249,115,22,.18)",
    },
  },
  {
    id: "arctic",
    name: "Arctic",
    icon: "arctic",
    fontId: "inter",
    cursor: "#06B6D4",
    preview: ["#F3FCFF", "#06B6D4", "#0F172A"],
    colors: {
      background: "#F3FCFF",
      backgroundSecondary: "#ECFEFF",
      surface: "#DFF7FB",
      surfaceHover: "#C8EEF5",
      text: "#0F172A",
      textSecondary: "#475569",
      primary: "#06B6D4",
      primaryHover: "#0891B2",
      success: "#22C55E",
      warning: "#F59E0B",
      danger: "#EF4444",
      border: "#BDECF3",
      shadow: "0 8px 24px rgba(6,182,212,.12)",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    icon: "dracula",
    fontId: "unbounded",
    cursor: "#BD93F9",
    preview: ["#282A36", "#BD93F9", "#F8F8F2"],
    colors: {
      background: "#282A36",
      backgroundSecondary: "#343746",
      surface: "#44475A",
      surfaceHover: "#50536A",
      text: "#F8F8F2",
      textSecondary: "#C8C8C2",
      primary: "#BD93F9",
      primaryHover: "#A855F7",
      success: "#50FA7B",
      warning: "#F1FA8C",
      danger: "#FF5555",
      border: "#6272A4",
      shadow: "0 8px 24px rgba(0,0,0,.45)",
    },
  },
  {
    id: "carbon",
    name: "Carbon",
    icon: "carbon",
    fontId: "syne",
    cursor: "#A855F7",
    preview: ["#09090B", "#A855F7", "#FAFAFA"],
    colors: {
      background: "#09090B",
      backgroundSecondary: "#18181B",
      surface: "#27272A",
      surfaceHover: "#3F3F46",
      text: "#FAFAFA",
      textSecondary: "#A1A1AA",
      primary: "#A855F7",
      primaryHover: "#9333EA",
      success: "#22C55E",
      warning: "#EAB308",
      danger: "#DC2626",
      border: "#3F3F46",
      shadow: "0 8px 24px rgba(0,0,0,.60)",
    },
  },
];

export { themes, fonts, themeIcons };
